package guibuilder;

import com.leapmotion.leap.Controller;
import javax.swing.JPanel;

/**
 *
 * @author Bora
 */
public class Login extends javax.swing.JFrame {

    private Controller controller;
    private  LeapListener listener;
     // Variables declaration - do not modify
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jUsernameField;




    /**
     * Creates new form Interface
     */
    public Login(Controller controller,  LeapListener listener) {
        this.controller = controller;
        this.listener = listener;
        initComponents();
    }

        public JPanel getLoginContainer() {
    return loginContainer;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginContainer = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        loginTitle = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        loginContainer.setOpaque(false);

        loginLabel.setFont(new java.awt.Font("UpsideDown", 0, 11)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(153, 255, 51));
        loginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/LOGIN1.jpg"))); // NOI18N

        passwordLabel.setFont(new java.awt.Font("UpsideDown", 0, 11)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 255, 51));
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/PASSWORD.jpg"))); // NOI18N

        confirmButton.setBackground(new java.awt.Color(0, 0, 0));
        confirmButton.setFont(new java.awt.Font("UpsideDown", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(0, 153, 153));
        confirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/OK BUTTON.jpg"))); // NOI18N
        confirmButton.setOpaque(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("UpsideDown", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(0, 153, 153));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/RETURN BUTTON.jpg"))); // NOI18N
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        loginTitle.setFont(new java.awt.Font("UpsideDown", 1, 24)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(0, 153, 153));
        loginTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/LOGINtitle.jpg"))); // NOI18N

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                        .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginContainerLayout.createSequentialGroup()
                                .addComponent(confirmButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton))
                            .addGroup(loginContainerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginContainerLayout.createSequentialGroup()
                                .addComponent(loginLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordLabel)))
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );

        loginContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField, jUsernameField});

        loginContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confirmButton, backButton});

        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(loginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {confirmButton, backButton});

        loginContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField, jUsernameField});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(loginContainer, gridBagConstraints);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guibuilder/newpackage/Logo - Copie1.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(logoLabel, gridBagConstraints);

        pack();
    }

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {
         Identification1 identification = new Identification1(controller, listener);
        loginContainer.removeAll();
        JPanel PanelIdentification = identification.getPanel();
        loginContainer.add(PanelIdentification);
        loginContainer.validate();
        loginContainer.repaint();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        // return
         Identification1 identification = new Identification1(controller, listener);
        //identification.setVisible(true);
        loginContainer.removeAll();
        JPanel PanelIdentification = identification.getPanel();
        loginContainer.add(PanelIdentification);
        loginContainer.validate();
        loginContainer.repaint();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       //         new Login().setVisible(true);
            }
        });
    }

   
}
